### PR TITLE
Fix capitalization

### LINKED ISSUE #95: Many streetnames are all uppercase
shouting allthestreetnames

```javascript
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      138.561943,
      -34.837527
    ]
  },
  "properties": {
    "id": "au/countrywide:1799337",
    "gid": "openaddresses:address:au/countrywide:1799337",
    "layer": "address",
    "source": "openaddresses",
    "name": "18 GLASGOW STREET",
    "housenumber": "18",
    "street": "GLASGOW STREET",
    ...
    "country_a": "AUS",
    "region": "South Australia",
    ...
  }
}
```

we could resolve this issue with some code like this:

```
if( name.IsAllCaps() ){
  name = name.LowerCase()
  for each word in name {
    uppercaseFirstChar( word )
  }
}
```

.. it wouldn't be perfect but considering it only works on names which are completely uppercase to begin with, it can't really get any worse than the original source data.

### PR DESCRIPTION
**Pull request by avulfson17**
Attempts to standardize capitalization in street names such that each word begins with a capital.

Fixes #95

### CODE REVIEW

**Comment by orangejulius** [comment]
:shipit:

**Comment by missinglink** [comment]
I'd love to see some tests in non latin alphabets. It wouldn't need to work for all languages, just best to check that it doesn't break japanese/thai/cyrillic/tamil etc.

**Comment by orangejulius** [comment]
@missinglink: @avulfson17 is [way ahead of you](https://github.com/pelias/openaddresses/pull/131/files#diff-8d82d41c4cee55e50d8a274fb6c7d398R131) :smiley:

File: test/streams/cleanupStream.js [hunk 1]
```diff
@@ -74,14 +74,73 @@ tape( 'cleanupStream trims leading 0\'s from house numbers', function(test) {
 
 tape ( 'cleanupStream trims white space in street field', function(test){
   var input = {
-      STREET: '34  West\t 93rd \nst'
+      STREET: '34  West\t 93rd \nSt'
```
Comment (dianashk) [inline test/streams/cleanupStream.js]: did the input have to change? shouldn't this have been tranformed to `St` anyway since the code tests each token in the input string separately?

Comment (dianashk) [inline test/streams/cleanupStream.js]: I guess this is just the test to verify that there is a chance that nothing is changed. All good.
